### ISSUE TITLE
Log what IP created/keeps alive which jobs

### ISSUE THREAD

**Issue by mossblaser** [SpiNNakerManchester/spalloc_server#1]
This should allow easier resolution of stray jobs which are being kept alive but by an unknown source...

**Comment by rowleya** [comment]
This could probably be done by having each job have a "last keepalive IP".  This would then indicate which IP address was last used to keep it alive (it is unlikely that any more than one IP address would be in use for this).

**Comment by alan-stokes** [comment]
pushed to later release due to none criticality

**Comment by dkfellows** [comment]
I've got this working now, and I'm working on improving the spalloc client to use the information.

**Comment by alan-stokes** [comment]
rubbered
